[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

# Force static site detection - disable all processing
[build.processing]
  skip_processing = true

# Disable all framework detection
[build.processing.css]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false

[build.processing.js]
  bundle = false
  minify = false

# Simple redirect to your main page
[[redirects]]
  from = "/*"
  to = "/simple-demo.html"
  status = 200

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
